Feat cgo-zstd
aliyun/aliyun-log-go-sdk pull request #284
Opened 2024-06-13 08:28 UTC by crimson-gao

2024-06-17 06:23 UTC, liketic commented on extensions/cgo-zstd/compressor.go
> +	zstd.NewCtx()
23 行 是做什么的

2024-06-17 06:25 UTC, liketic commented on compressor.go
> +var DefaultZstdCompressor LogCompressor = NewZstdCompressor(zstd.SpeedFastest)
DefaultZstdCompressor，这个名称是 Default，是允许修改吗？直接是 ZstdCompressor 是不是好点

2024-06-17 14:18 UTC, crimson-gao commented on compressor.go
> +var DefaultZstdCompressor LogCompressor = NewZstdCompressor(zstd.SpeedFastest)
允许修改

2024-06-17 14:34 UTC, crimson-gao commented on compressor.go
> +var DefaultZstdCompressor LogCompressor = NewZstdCompressor(zstd.SpeedFastest)
比如这样 compressLevel := 1
sls.DefaultZstdCompressor = cgozstd.NewZstdCompressor(compressLevel)

2024-06-17 14:34 UTC, crimson-gao commented on compressor.go
> +var DefaultZstdCompressor LogCompressor = NewZstdCompressor(zstd.SpeedFastest)
compressLevel := 1
sls.DefaultZstdCompressor = cgozstd.NewZstdCompressor(compressLevel)

2024-07-30 11:12 UTC, liketic requested changes

2024-07-30 11:12 UTC, liketic commented on compressor.go
> +var DefaultZstdCompressor LogCompressor = NewZstdCompressor(zstd.SpeedFastest)
DefaultZstdCompressor =》ZstdCompressor

2024-07-30 11:12 UTC, liketic commented on extensions/cgo-zstd/README.md
> +cgo-zstd 是基于 cgo 实现的 zstd 压缩库，比纯 go 实现的 zstd 在性能上具有一定优势。
我在想，能不能就搞一个 internal/zstd_cgo.go 这样一个文件。我们还有什么内容是需要放到这里的？

2024-07-30 11:14 UTC, liketic commented on compressor.go
> +var DefaultZstdCompressor LogCompressor = NewZstdCompressor(zstd.SpeedFastest)
或者，能不能搞一个函数
```
sls.SetZstdCgoCompressor(compressLevel int)
```

2024-07-31 05:55 UTC, crimson-gao commented on compressor.go
> +var DefaultZstdCompressor LogCompressor = NewZstdCompressor(zstd.SpeedFastest)
不能直接引用，只能外挂

2024-07-31 06:18 UTC, liketic commented on cgo/README.md
> +下面介绍如何开启此扩展来提升 zstd 压缩的性能。
1-3 行直接去掉好了

2024-07-31 07:04 UTC, merged